export {
  environmentRequiresRpcAssetTransport,
  getEnvironmentHttpBaseUrl,
  getSavedEnvironmentRecord,
  getSavedEnvironmentRuntimeState,
  hasSavedEnvironmentRegistryHydrated,
  listSavedEnvironmentRecords,
  readEnvironmentDescriptor,
  readSavedEnvironmentBearerToken,
  resetSavedEnvironmentRegistryStoreForTests,
  resetSavedEnvironmentRuntimeStoreForTests,
  resolveEnvironmentHttpUrl,
  useSavedEnvironmentRegistryStore,
  useSavedEnvironmentRuntimeStore,
  waitForSavedEnvironmentRegistryHydration,
  type SavedEnvironmentRecord,
  type SavedEnvironmentRuntimeState,
} from "./catalog";

export {
  addSavedEnvironment,
  connectDesktopSshEnvironment,
  disconnectSavedEnvironment,
  ensureEnvironmentConnectionBootstrapped,
  getPrimaryEnvironmentConnection,
  markRelaySavedEnvironmentLinkExpired,
  readBackendEnvironmentConnection,
  readEnvironmentConnection,
  reconnectSavedEnvironment,
  RELAY_LINK_EXPIRED_MESSAGE,
  removeSavedEnvironment,
  requireEnvironmentConnection,
  resetEnvironmentServiceForTests,
  startEnvironmentConnectionService,
  subscribeEnvironmentConnections,
} from "./service";

export { readRelayDeviceCredentials } from "./relayCredentials";
export {
  cancelPendingRelayJoin,
  canJoinWithCode,
  isPendingRelayJoin,
  RelayJoinError,
  startCodeJoin,
  startInviteClaim,
  startRelayJoinWatchers,
  useRelayJoinStore,
  type RelayJoinAccepted,
  type RelayJoinOutcome,
  type SubmitCodeJoinViaServer,
} from "./relayJoins";
