import { createECDH } from "node:crypto";

import { describe, expect, it } from "vite-plus/test";

import {
  claimProof,
  claimSecrets,
  fromUtf8,
  type NoiseKeyPair,
  P256,
  pairingCommitment,
  pairingMatchNumber,
  SecureStream,
  type SecureTransport,
  SECURE_FRAME_DATA_PART,
  SECURE_PART_BYTES,
  SECURE_RECORD_APP,
  securePrologue,
  startKKInitiator,
  startKKResponder,
  toBase64Url,
  utf8,
  verifyClaimProof,
  X25519,
} from "./relaySecure.ts";

/**
 * Generated by the Python `noiseprotocol` package (an independent Noise
 * implementation) with fixed static and ephemeral keys.
 */
const REFERENCE = {
  protocol: "Noise_KK_25519_AESGCM_SHA256",
  prologue: "7468726561646c696e65732d746573742d70726f6c6f677565",
  initiatorStatic: {
    pkcs8:
      "302e020100300506032b656e042204200102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
    public: "07a37cbc142093c8b755dc1b10e86cb426374ad16aa853ed0bdfc0b2b86d1c7c",
  },
  responderStatic: {
    pkcs8:
      "302e020100300506032b656e0422042032333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f5051",
    public: "e05b1ae322024838095ffdefd865468ddb77b14b2dd275175ea0ab4294fa6d7a",
  },
  initiatorEphemeral: {
    pkcs8:
      "302e020100300506032b656e042204206465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80818283",
    public: "7d9c24316539825c1896e57f28197746793ce60cbee3ad47da9d07b85fa55e2a",
  },
  responderEphemeral: {
    pkcs8:
      "302e020100300506032b656e04220420969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5",
    public: "08264ae690b411d8e3ede40f87192585ea114a082744a776105aac05eab1052e",
  },
  message1Payload: "68656c6c6f2066726f6d2074686520646576696365",
  message1:
    "7d9c24316539825c1896e57f28197746793ce60cbee3ad47da9d07b85fa55e2af7c09306601953e75c5867ec71c8f13114b9c9c6bdcddb054fa7f72197a1fea6ac2dfcd843",
  message2:
    "08264ae690b411d8e3ede40f87192585ea114a082744a776105aac05eab1052e5436ef4e2aed798e8102b8d81b22df25",
  handshakeHash: "4431e190eba94eb7a8dc8deb5b8f86d5a3e7ce20b22bd9c8bec36c94910600e0",
  transport: [
    {
      from: "initiator",
      plaintext: "6669727374207472616e73706f7274206d657373616765",
      ciphertext: "7248c5fd014f15b4aa54a0d574972a90d1d15655abdc88b48bc451afa392a3df10c96e770480ac",
    },
    {
      from: "responder",
      plaintext: "7365636f6e642c2066726f6d2074686520686f7374",
      ciphertext: "ffd5a649f4cac840c767546af582f7a0af88e1cd05289286a7aaccaf22e4044eebd899e21e",
    },
    {
      from: "initiator",
      plaintext: "7468697264",
      ciphertext: "3c0ba8b21036c5ad7992ecb111805b14a34c641418",
    },
  ],
} as const;

const hex = (text: string) =>
  Uint8Array.from(text.match(/../gu) ?? [], (byte) => parseInt(byte, 16));
const toHex = (bytes: Uint8Array) =>
  Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
const loadX25519 = (key: { readonly pkcs8: string; readonly public: string }) =>
  X25519.importKeyPair(hex(key.pkcs8), hex(key.public));

async function p256Pair() {
  const [device, host] = await Promise.all([P256.generateKeyPair(), P256.generateKeyPair()]);
  return { device, host };
}

async function handshake(
  device: NoiseKeyPair,
  host: NoiseKeyPair,
  options: { readonly hostExpects?: Uint8Array; readonly hostPrologue?: Uint8Array } = {},
): Promise<{ readonly device: SecureTransport; readonly host: SecureTransport }> {
  const prologue = securePrologue("host-1", "device-1");
  const initiator = await startKKInitiator({
    staticKeyPair: device,
    remoteStaticPublicKey: host.publicKey,
    prologue,
  });
  const responder = await startKKResponder({
    staticKeyPair: host,
    remoteStaticPublicKey: options.hostExpects ?? device.publicKey,
    prologue: options.hostPrologue ?? prologue,
  });
  await responder.readMessage1(await initiator.writeMessage1());
  const reply = await responder.writeMessage2();
  const finished = await initiator.readMessage2(reply.message);
  return { device: finished.transport, host: reply.transport };
}

describe("Noise KK", () => {
  it("matches an independent implementation byte for byte", async () => {
    const prologue = hex(REFERENCE.prologue);
    const initiator = await startKKInitiator({
      dh: X25519,
      protocolName: REFERENCE.protocol,
      staticKeyPair: await loadX25519(REFERENCE.initiatorStatic),
      remoteStaticPublicKey: hex(REFERENCE.responderStatic.public),
      ephemeralKeyPair: await loadX25519(REFERENCE.initiatorEphemeral),
      prologue,
    });
    const responder = await startKKResponder({
      dh: X25519,
      protocolName: REFERENCE.protocol,
      staticKeyPair: await loadX25519(REFERENCE.responderStatic),
      remoteStaticPublicKey: hex(REFERENCE.initiatorStatic.public),
      ephemeralKeyPair: await loadX25519(REFERENCE.responderEphemeral),
      prologue,
    });

    const message1 = await initiator.writeMessage1(hex(REFERENCE.message1Payload));
    expect(toHex(message1)).toBe(REFERENCE.message1);
    expect(toHex(await responder.readMessage1(message1))).toBe(REFERENCE.message1Payload);
    const reply = await responder.writeMessage2();
    expect(toHex(reply.message)).toBe(REFERENCE.message2);
    const finished = await initiator.readMessage2(reply.message);
    expect(toHex(finished.transport.handshakeHash)).toBe(REFERENCE.handshakeHash);

    for (const step of REFERENCE.transport) {
      const [sender, receiver] =
        step.from === "initiator"
          ? [finished.transport, reply.transport]
          : [reply.transport, finished.transport];
      const ciphertext = await sender.send.encryptWithAd(new Uint8Array(0), hex(step.plaintext));
      expect(toHex(ciphertext)).toBe(step.ciphertext);
      expect(toHex(await receiver.receive.decryptWithAd(new Uint8Array(0), ciphertext))).toBe(
        step.plaintext,
      );
    }
  });

  it("agrees on P-256 with the platform ECDH, and refuses points off the curve", async () => {
    const pair = await P256.generateKeyPair();
    const node = createECDH("prime256v1");
    node.generateKeys();
    const expected = node.computeSecret(Buffer.from(pair.publicKey));
    const actual = await P256.dh(pair.privateKey, await P256.importPublicKey(node.getPublicKey()));
    expect(toHex(actual)).toBe(expected.toString("hex"));

    const offCurve = new Uint8Array(pair.publicKey);
    offCurve[64] = offCurve[64]! ^ 0x01;
    await expect(P256.importPublicKey(offCurve)).rejects.toThrow();
  });

  it("only completes between the keys each side expects, under the same prologue", async () => {
    const { device, host } = await p256Pair();
    const good = await handshake(device, host);
    expect(toHex(good.device.handshakeHash)).toBe(toHex(good.host.handshakeHash));

    const stranger = await P256.generateKeyPair();
    await expect(handshake(stranger, host, { hostExpects: device.publicKey })).rejects.toThrow();
    await expect(
      handshake(device, host, { hostPrologue: securePrologue("host-1", "device-2") }),
    ).rejects.toThrow();
  });
});

describe("SecureStream", () => {
  async function connectedStreams() {
    const { device, host } = await p256Pair();
    const transports = await handshake(device, host);
    const toHost: Array<Uint8Array> = [];
    const received: Array<string> = [];
    const errors: Array<string> = [];
    const sender = new SecureStream({
      transport: transports.device,
      sendFrame: (frame) => toHost.push(frame),
      onRecord: () => undefined,
      onError: (reason) => errors.push(reason),
    });
    const receiver = new SecureStream({
      transport: transports.host,
      sendFrame: () => undefined,
      onRecord: (type, body) => {
        if (type === SECURE_RECORD_APP) received.push(fromUtf8(body));
      },
      onError: (reason) => errors.push(reason),
    });
    const flush = () => new Promise((resolve) => setTimeout(resolve, 20));
    return { sender, receiver, toHost, received, errors, flush };
  }

  it("delivers messages in order, splitting large ones into parts", async () => {
    const { sender, receiver, toHost, received, errors, flush } = await connectedStreams();
    // A big first message too: a host's first answer can be a large snapshot.
    const large = "x".repeat(SECURE_PART_BYTES * 10 + 10);
    sender.sendText(large);
    sender.sendText("second");
    sender.sendText(large);
    await flush();
    expect(toHost.length).toBe(23);
    for (const frame of toHost) receiver.receiveFrame(frame);
    await flush();
    expect(received).toEqual([large, "second", large]);
    expect(errors).toEqual([]);
  });

  it("stops on a dropped, replayed, or altered message", async () => {
    for (const tamper of ["drop", "replay", "flip", "empty-part"] as const) {
      const { sender, receiver, toHost, received, errors, flush } = await connectedStreams();
      sender.sendText("one");
      sender.sendText("two");
      await flush();
      const [one, two] = toHost as [Uint8Array, Uint8Array];
      const frames =
        tamper === "drop"
          ? [two]
          : tamper === "replay"
            ? [one, one, two]
            : tamper === "flip"
              ? [Uint8Array.from(one, (byte, index) => (index === 3 ? byte ^ 1 : byte)), two]
              : // Padding the buffer with empty parts is refused before anything grows.
                [new Uint8Array([SECURE_FRAME_DATA_PART]), one, two];
      for (const frame of frames) receiver.receiveFrame(frame);
      await flush();
      expect(errors.length, tamper).toBe(1);
      expect(received.length, tamper).toBeLessThanOrEqual(1);
      expect(received.includes("two"), tamper).toBe(false);
    }
  });
});

describe("pairing", () => {
  it("shows the same 4-digit number on both sides, and a different one if any input changes", async () => {
    const { device, host } = await p256Pair();
    const input = {
      hostPublicKey: host.publicKey,
      devicePublicKey: device.publicKey,
      hostNonce: utf8("host-nonce-16byt"),
      deviceNonce: utf8("device-nonce-16b"),
    };
    const number = await pairingMatchNumber(input);
    expect(number).toMatch(/^\d{4}$/u);
    expect(await pairingMatchNumber({ ...input })).toBe(number);
    const others = await Promise.all(
      Array.from({ length: 20 }, (_, index) =>
        pairingMatchNumber({ ...input, hostNonce: utf8(`other-nonce-${index}`) }),
      ),
    );
    expect(others.filter((other) => other !== number).length).toBeGreaterThan(15);
    expect(await pairingCommitment(device.publicKey, input.deviceNonce)).not.toBe(
      await pairingCommitment(device.publicKey, input.hostNonce),
    );
  });

  it("accepts a QR claim proof only for the same invite, join, and key", async () => {
    const { device } = await p256Pair();
    const secret = utf8("an invite secret that is 32 byte");
    const { macKey, claimToken } = await claimSecrets(secret);
    expect(claimToken).not.toBe(toBase64Url(macKey));
    const claim = {
      macKey,
      inviteId: "invite-1",
      joinId: "join-1",
      devicePublicKey: device.publicKey,
    };
    const proof = await claimProof(claim);
    expect(await verifyClaimProof({ ...claim, proof })).toBe(true);
    expect(await verifyClaimProof({ ...claim, joinId: "join-2", proof })).toBe(false);
    const other = await P256.generateKeyPair();
    expect(await verifyClaimProof({ ...claim, devicePublicKey: other.publicKey, proof })).toBe(
      false,
    );
  });
});
